
name: Subfinder - Subdomain Finder

on: issue_comment

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
          
      - name: 🔎 SubFinder - DNS Enumeration
        uses: projectdiscovery/subfinder-action@main
        with:
          domain: ${{ github.event.comment.body }}
          flags: "-silent"

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: subfinder.log
          path: subfinder.log
